### ISSUE TITLE
Ubuntu focal - focal Release' does not have a Release file

### ISSUE THREAD

**Issue by palansher** [fauust/ansible-role-mariadb#11]
Hello! 

Thanks for the role!

problem is on ubuntu 20.04:

> TASK [mariadb : Setup mariadb repository sourcelist entry] *******************************************************************************************************************************************
> fatal: [gtprod]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://mirror.docker.ru/mariadb/repo/10.5/debian focal Release' does not have a Release file."}

But if I change the url:
```
# repo: deb {{ mariadb_use_official_repo_url }}/{{ mariadb_use_official_repo_version }}/debian {{ ansible_distribution_release }} main
    repo: deb {{ mariadb_use_official_repo_url }}/{{ mariadb_use_official_repo_version }}/ubuntu {{ ansible_distribution_release }} main
```

- everything is ok.
-

**Comment by fauust** [comment]
Hi @palansher thank you for your report.
Do you feel creating a pull to resolve this issue?

**Comment by palansher** [comment]
Hello! 

Sorry, I'm just starting to learn ansible. I feel I can more destroy than fix on my current level :)
