### ISSUE TITLE
Create a step in CI that would setup a replica

### ISSUE THREAD

**Issue by colmtroy** [fauust/ansible-role-mariadb#26]
Great work on this role @fauust ! 
I also enjoyed [your video](https://www.youtube.com/watch?v=CV8-56Fgjc0) :) 

(Aside, you should ask for [this page](https://mariadb.com/kb/en/existing-ansible-modules-and-roles-for-mariadb/) to be updated to specifically link to your role as it's by far the most relevant to MariaDB.

So I have my own MariaDB role which I'm considering ditching and moving to using your role, but I'm curious as to what advice you would have for setting up a replica for an existing MariaDB DB that's approx. 15GB.

From the looks of things, the replication tasks in your role pretty much assume a clean install of both the primary and replica at the same time right? 

e.g. Looking [at the docs](https://mariadb.com/kb/en/setting-up-a-replica-with-mariabackup/) you would typically:
- lock the db and back it up (although locking tables doesn't look to be called out as a requirement when using mariabackup?)
- unlock it 
- move and restore the backup on the replica 
- grab the GTID coordinates and set gtid_slave_pos and MASTER_USE_GTID and start the slave

I'm struggling with how I should write a role to automate the replica setup process when factoring in moving a DB backup in this manner.

Any advice?

**Comment by fauust** [comment]
Hi @colmtroy!
> Great work on this role @fauust !
> I also enjoyed [your video](https://www.youtube.com/watch?v=CV8-56Fgjc0) :)

Thanks!

> (Aside, you should ask for [this page](https://mariadb.com/kb/en/existing-ansible-modules-and-roles-for-mariadb/) to be updated to specifically link to your role as it's by far the most relevant to MariaDB.

Yep, I will. The video is listed there though.

> From the looks of things, the replication tasks in your role pretty much assume a clean install of both the primary and replica at the same time right?

Exact.

> lock the db and back it up (although locking tables doesn't look to be called out as a requirement when using mariabackup?)

Yes, definitively use mariabackup for that task to avoid locks. Here is the reference documentation https://mariadb.com/kb/en/setting-up-a-replica-with-mariabackup and you can take a look at https://www.youtube.com/watch?v=dQRuK7y2zuc that is a very good presentation on mariadbackup IMO.

> unlock it

not needed if you use mariabackup

> move and restore the backup on the replica

Yes

> grab the GTID coordinates and set gtid_slave_pos and MASTER_USE_GTID and start the slave

Yes, you have to get those from the `xtrabackup_binlog_info file, see https://mariadb.com/kb/en/setting-up-a-replica-with-mariabackup/#start-replication-on-the-new-replica.

> I'm struggling with how I should write a role to automate the replica setup process when factoring in moving a DB backup in this manner.

I am not sure that an ansible role is the best approach for such a task. Roles are re-usable things/modules and this is a very specific task that depends on very specific setup (like where the backup is going to be, how you will copy it on the replica; etc.). And trying to create a role to take all this specs in consideration is maybe too complicated...?

So you could create a simple playbook that will do what you have listed previously and in that order. It's up to you to decide if you want that the playbook also manage backup and copy to the replica...

Good luck!

**Comment by colmtroy** [comment]
Thanks @fauust for the very detailed reply!
You helped to clarify many things for me :) 

In an effort to try and store my entire web app setup as code I had started going down the road of making a playbook similar [to this](https://github.com/ekeih/setup-mysql-slave/blob/master/main.yml) to try and automate my replica setup entirely, but I think I'm quickly coming to the conclusion that there's so many edge cases that it might make more sense to leave this specific replica use case setup as a partially manual task.

I have most of it automated now except the mariadb-backup backup/restore process and the setting of the global gtid_slave_pos variable.

I rolled my own replica role based on yours.

BTW: `changemaster` with `master_use_gtid` does indeed now work [theres just a missing closing double quote here](https://github.com/fauust/ansible-role-mariadb/blob/main/tasks/replication_replica.yml#L28). 

I also had to remove the `resetreplica` [task](https://github.com/fauust/ansible-role-mariadb/blob/990a494441a015b53a50fbf02f41c8147d969f96/tasks/replication_replica.yml#L35) in order for my replica to start correctly. 

Through a process of trial and error, I found that when the resetreplica task was present, the replica would throw some errors
e.g.

`                Last_SQL_Error: Error 'Operation CREATE USER failed for 'replu5rss0t'@'localhost'' on query. Default database: ''. Query: 'CREATE USER 'replu5rss0t'@'localhost' IDENTIFIED WITH mysql_native_password AS 'redacted'`

But overall i'm pretty happy that manual intervention is now very minimal thanks to your work 👍

**Comment by fauust** [comment]
> BTW: changemaster with master_use_gtid does indeed now work [theres just a missing closing double quote here](https://github.com/fauust/ansible-role-mariadb/blob/main/tasks/replication_replica.yml#L28).

Ok thanks, that's a good news, before activating it I will have to do some tests with recent version of Ansible. I see that my molecule test does not actually check the replication setup (only user setup) so I will probably try to take some time to check if that's a test that can be added too in my role testing.

> I also had to remove the resetreplica [task](https://github.com/fauust/ansible-role-mariadb/blob/990a494441a015b53a50fbf02f41c8147d969f96/tasks/replication_replica.yml#L35) in order for my replica to start correctly.

I'll probably have to test that too. Thanks for the warning!
