### ISSUE TITLE
System tables not initialized on Debian 11 - Mariadb 10.5

### ISSUE THREAD

**Issue by sbourdette** [fauust/ansible-role-mariadb#33]
When trying ton install mariadb 10.5 with mariadb repo on debian 11.

Mariadb failed to start because it doesn't find systm tables.

I had to add this task in configure.yml before starting the service : 

- name: Run mysql_install_db
  ansible.builtin.command:
    cmd: "mysql_install_db -u {{ mariadb_user }}"

Do I miss something ?

Custom variables used : 

I had to modify mariadb_basic_settings_raw to add ignore_db_dirs because my /var/lib/mysql is on a specific disk/partition

```
mariadb_use_official_repo: true
mariadb_use_official_repo_version: 10.5

mariadb_basic_settings_raw: |
  user                  = {{ mariadb_user }}
  pid-file              = {{ mariadb_pid_file }}
  socket                = {{ mariadb_unix_socket }}
  basedir               = /usr
  datadir               = {{ mariadb_data_dir }}
  tmpdir                = /tmp
  lc-messages-dir       = /usr/share/mysql
  lc_messages           = en_US
  skip-external-locking
  port                  = {{ mariadb_port }}
  bind-address          = {{ mariadb_bind_address }}
  ignore_db_dirs        = lost+found
```

**Comment by fauust** [comment]
Hi!
I am not sure that I understand the exact pb. System tables should be installed by default on new MariaDB deployments, if the `datadir` changes after installation, then yes they need to be re-created.

The Debian 11 / 10.5 (from MDBF repo) installation from scratch is tested in CI, see https://github.com/fauust/ansible-role-mariadb/actions/runs/4229541331/jobs/7346007688 and works well...

**Comment by fauust** [comment]
Please re-open if you can provide steps on how to show the issue.
